# Generated by Django 6.0.4 on 2026-04-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='news',
        ),
        migrations.AddField(
            model_name='category',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='news.article', verbose_name='Новини'),
        ),
    ]
